version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: teamtick-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: teamtick
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped

  redis:
    image: redis:latest
    container_name: teamtick-redis
    ports:
      - "6379:6379"
    restart: always

volumes:
  mysql_data: 